[Interface]
PrivateKey = WOwxGOdgCwUTE33eTuc/t4OwCOb3yQRWmXruspXJ+GM=
Address = 10.0.0.2/24
DNS = 8.8.8.8, 1.1.1.1

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
Endpoint = 162.159.193.1:2408
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
