[Interface]
PrivateKey = IHdrgLxHwY0FTGAN2pbFgNHR5A5BPy/Q86GfkycSLmA=
Address = 10.7.0.1/24
ListenPort = 51821

[Peer]
PublicKey = dN3oqapWHsoCEM4k0+va83Q7EouZH6dP86ZBDA484Eo=
AllowedIPs = 10.7.0.2/32
