[Interface]
PrivateKey = YMsokbD7aKxw6P+GhlnUU4NL0fI0Rs3pEcpIYGoQdGo=
Address = 10.7.0.1/24
ListenPort = 51822

[Peer]
PublicKey = 5YZ9jeGYHan73GMQi54qPsF2TQruyQAvsz7Gb00cdUM=
AllowedIPs = 10.7.0.2/32
