[Interface]
PrivateKey = cKdhrbH9tQ63bsSTIRGDbot2i4LtGSZ4sbL5ur3kYGQ=
Address = 10.0.0.1/24
ListenPort = 51820

[Peer]
PublicKey = 8Bit9LFfDrBsfv7rnWP5Ze41Zh/2Jq/g67uFTZH/bXI=
AllowedIPs = 10.0.0.2/32
